/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Person;
import com.sun.jdi.Value;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Seemin
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
     private Person person;
     
     public CreateJPanel(Person person) {
     initComponents();
     this.person = person;
         
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PhotoLbl = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        pic1Lbl = new javax.swing.JLabel();
        BroswePic1Btn = new javax.swing.JButton();
        pic2Lbl = new javax.swing.JLabel();
        HealthPlanNoLbl = new javax.swing.JLabel();
        TelPh2TextField = new javax.swing.JTextField();
        GeographicDataTextField = new javax.swing.JTextField();
        HealthPlanNoTextField = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        BankAccNoLbl = new javax.swing.JLabel();
        GeographicDataLbl = new javax.swing.JLabel();
        BankAccNo1TextField = new javax.swing.JTextField();
        Email1TextField = new javax.swing.JTextField();
        BankAccNo2TextField = new javax.swing.JTextField();
        DateofBirthLbl = new javax.swing.JLabel();
        LicenseNoLbl = new javax.swing.JLabel();
        TelPh1TextField = new javax.swing.JTextField();
        DateofBirthTextField1 = new javax.swing.JTextField();
        TelPhnLbl = new javax.swing.JLabel();
        LicenseNoTextField = new javax.swing.JTextField();
        LinkedInLbl = new javax.swing.JLabel();
        VehicleIdentifierLbl = new javax.swing.JLabel();
        LinkedInTextField = new javax.swing.JTextField();
        Email2TextField = new javax.swing.JTextField();
        VehicleID1TextField = new javax.swing.JTextField();
        VehicleID2TextField = new javax.swing.JTextField();
        IPLbl = new javax.swing.JLabel();
        DeviceIDLbl = new javax.swing.JLabel();
        SSNLbl = new javax.swing.JLabel();
        BiometricLbl = new javax.swing.JLabel();
        IPTextField = new javax.swing.JTextField();
        BiometricTextField = new javax.swing.JTextField();
        SSNTextField = new javax.swing.JTextField();
        UniqueIDLbl = new javax.swing.JLabel();
        FaxNoTextField = new javax.swing.JTextField();
        UniqueIDTextField = new javax.swing.JTextField();
        CreatLbl = new javax.swing.JLabel();
        MedicalNoLbl = new javax.swing.JLabel();
        FaxNoLbl = new javax.swing.JLabel();
        MedicalNoTextField = new javax.swing.JTextField();
        DeviceID1TextField = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        DeviceID2TextField = new javax.swing.JTextField();
        BroswePic2Btn = new javax.swing.JButton();

        PhotoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        PhotoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PhotoLbl.setText("Full Face Photos ** :");

        SaveBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        SaveBtn.setText("SAVE PROFILE");
        SaveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        pic1Lbl.setBackground(new java.awt.Color(0, 204, 204));
        pic1Lbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        pic1Lbl.setForeground(new java.awt.Color(153, 153, 153));
        pic1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic1Lbl.setText("Pic 1");
        pic1Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BroswePic1Btn.setActionCommand("Broswe Pic ");
        BroswePic1Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BroswePic1Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BroswePic1Btn.setLabel("Broswe 1");
        BroswePic1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroswePic1BtnActionPerformed(evt);
            }
        });

        pic2Lbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        pic2Lbl.setForeground(new java.awt.Color(153, 153, 153));
        pic2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic2Lbl.setText("Pic 2");
        pic2Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HealthPlanNoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        HealthPlanNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HealthPlanNoLbl.setText("Health Plan Beneficiary Number :");
        HealthPlanNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TelPh2TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        TelPh2TextField.setForeground(new java.awt.Color(153, 153, 153));
        TelPh2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TelPh2TextField.setText("Home No");
        TelPh2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelPh2TextFieldActionPerformed(evt);
            }
        });

        GeographicDataTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        GeographicDataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeographicDataTextFieldActionPerformed(evt);
            }
        });

        HealthPlanNoTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        HealthPlanNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthPlanNoTextFieldActionPerformed(evt);
            }
        });

        EmailLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        EmailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EmailLbl.setText("Email Address :");

        BankAccNoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BankAccNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BankAccNoLbl.setText("Bank Account Number :");

        GeographicDataLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        GeographicDataLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GeographicDataLbl.setText("Geographic Data :");
        GeographicDataLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BankAccNo1TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BankAccNo1TextField.setForeground(new java.awt.Color(153, 153, 153));
        BankAccNo1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BankAccNo1TextField.setText("Account 1");
        BankAccNo1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankAccNo1TextFieldActionPerformed(evt);
            }
        });

        Email1TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Email1TextField.setForeground(new java.awt.Color(153, 153, 153));
        Email1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email1TextField.setText("Email 1");
        Email1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email1TextFieldActionPerformed(evt);
            }
        });

        BankAccNo2TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BankAccNo2TextField.setForeground(new java.awt.Color(153, 153, 153));
        BankAccNo2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BankAccNo2TextField.setText("Account 2");
        BankAccNo2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankAccNo2TextFieldActionPerformed(evt);
            }
        });

        DateofBirthLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DateofBirthLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DateofBirthLbl.setText("Date of Birth : ");

        LicenseNoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        LicenseNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LicenseNoLbl.setText("Certificate/ License Number :");

        TelPh1TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        TelPh1TextField.setForeground(new java.awt.Color(153, 153, 153));
        TelPh1TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TelPh1TextField.setText("Work No");
        TelPh1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelPh1TextFieldActionPerformed(evt);
            }
        });

        DateofBirthTextField1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DateofBirthTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateofBirthTextField1ActionPerformed(evt);
            }
        });

        TelPhnLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        TelPhnLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TelPhnLbl.setText("Telephone Number : ");

        LicenseNoTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        LicenseNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseNoTextFieldActionPerformed(evt);
            }
        });

        LinkedInLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        LinkedInLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LinkedInLbl.setText("LinkedIn :");

        VehicleIdentifierLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        VehicleIdentifierLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        VehicleIdentifierLbl.setText("Vehicle Identifiers :");

        LinkedInTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        LinkedInTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkedInTextFieldActionPerformed(evt);
            }
        });

        Email2TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        Email2TextField.setForeground(new java.awt.Color(153, 153, 153));
        Email2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email2TextField.setText("Email 2");
        Email2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email2TextFieldActionPerformed(evt);
            }
        });

        VehicleID1TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        VehicleID1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleID1TextFieldActionPerformed(evt);
            }
        });

        VehicleID2TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        VehicleID2TextField.setForeground(new java.awt.Color(153, 153, 153));
        VehicleID2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VehicleID2TextField.setText("License Plate No");
        VehicleID2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleID2TextFieldActionPerformed(evt);
            }
        });

        IPLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        IPLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IPLbl.setText("IP Address :");

        DeviceIDLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DeviceIDLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DeviceIDLbl.setText("Device Identifiers :");

        SSNLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        SSNLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SSNLbl.setText("Social Security Number :");

        BiometricLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BiometricLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BiometricLbl.setText("Biometric Identifiers :");

        IPTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        IPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPTextFieldActionPerformed(evt);
            }
        });

        BiometricTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        BiometricTextField.setForeground(new java.awt.Color(153, 153, 153));
        BiometricTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BiometricTextField.setText("Retinal scan, fingerprints, etc");
        BiometricTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiometricTextFieldActionPerformed(evt);
            }
        });

        SSNTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        SSNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNTextFieldActionPerformed(evt);
            }
        });

        UniqueIDLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        UniqueIDLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UniqueIDLbl.setText("Any unique Identifying No :");

        FaxNoTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        FaxNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaxNoTextFieldActionPerformed(evt);
            }
        });

        UniqueIDTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        UniqueIDTextField.setForeground(new java.awt.Color(153, 153, 153));
        UniqueIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UniqueIDTextField.setText("Characteristic or code");
        UniqueIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniqueIDTextFieldActionPerformed(evt);
            }
        });

        CreatLbl.setBackground(new java.awt.Color(255, 255, 0));
        CreatLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        CreatLbl.setForeground(new java.awt.Color(51, 51, 255));
        CreatLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreatLbl.setText("CREATE PERSON PROFILE");
        CreatLbl.setToolTipText("");
        CreatLbl.setBorder(new javax.swing.border.MatteBorder(null));
        CreatLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreatLbl.setInheritsPopupMenu(false);

        MedicalNoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        MedicalNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MedicalNoLbl.setText("Medical Record Number : ");
        MedicalNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        FaxNoLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        FaxNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FaxNoLbl.setText("FAX Number :");

        MedicalNoTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        MedicalNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalNoTextFieldActionPerformed(evt);
            }
        });

        DeviceID1TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DeviceID1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceID1TextFieldActionPerformed(evt);
            }
        });

        NameLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        NameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLbl.setText("Name : ");
        NameLbl.setToolTipText("");

        NameTextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        DeviceID2TextField.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DeviceID2TextField.setForeground(new java.awt.Color(153, 153, 153));
        DeviceID2TextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DeviceID2TextField.setText("Serial No");
        DeviceID2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceID2TextFieldActionPerformed(evt);
            }
        });

        BroswePic2Btn.setActionCommand("Broswe Pic ");
        BroswePic2Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BroswePic2Btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BroswePic2Btn.setLabel("Broswe 2");
        BroswePic2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroswePic2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(GeographicDataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelPhnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MedicalNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BankAccNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TelPh1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TelPh2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Email1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DateofBirthLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FaxNoLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SSNLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FaxNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DateofBirthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Email2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BankAccNo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BankAccNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MedicalNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(HealthPlanNoLbl)
                                        .addGap(39, 39, 39)))
                                .addComponent(HealthPlanNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VehicleIdentifierLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LicenseNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LicenseNoTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(VehicleID1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LinkedInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LinkedInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IPLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VehicleID2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CreatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeviceIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(DeviceID1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BiometricLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UniqueIDLbl)
                                    .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GeographicDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(BiometricTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UniqueIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeviceID2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(BroswePic1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(BroswePic2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CreatLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateofBirthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateofBirthLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GeographicDataLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FaxNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FaxNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeographicDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelPhnLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelPh1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelPh2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedicalNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HealthPlanNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HealthPlanNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BankAccNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankAccNo1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankAccNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LinkedInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LinkedInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LicenseNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IPLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VehicleID2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VehicleIdentifierLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VehicleID1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeviceIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeviceID1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeviceID2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BiometricLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BiometricTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UniqueIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UniqueIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pic1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pic2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BroswePic1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BroswePic2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String name = NameTextField.getText();
        String date = DateofBirthTextField1.getText();
        String geographicalData = GeographicDataTextField.getText();
        int faxNo = Integer.parseInt(FaxNoTextField.getText());
        long telPhn1 = Long.parseLong(TelPh1TextField.getText());
        long telPhn2 = Long.parseLong(TelPh2TextField.getText());
        int ssnNo = Integer.parseInt(SSNTextField.getText());
        String email1 = Email1TextField.getText();
        String email2 = Email1TextField.getText();
        int medNo = Integer.parseInt(MedicalNoTextField.getText());
        int hpbNo = Integer.parseInt(HealthPlanNoTextField.getText());
        long bankacc1 = Long.parseLong(BankAccNo1TextField.getText());
        long bankacc2 = Long.parseLong(BankAccNo2TextField.getText());
        String linkedin = LinkedInTextField.getText();
        int license = Integer.parseInt(LicenseNoTextField.getText());
        long ipAdd = Long.parseLong(IPTextField.getText());
        int vehicleID1 = Integer.parseInt(VehicleID1TextField.getText());
        int licensePlateNo = Integer.parseInt(VehicleID2TextField.getText());
        int deviceID = Integer.parseInt(DeviceID1TextField.getText());
        int serialNo = Integer.parseInt(DeviceID2TextField.getText());
        String bioID = BiometricTextField.getText();
        String uniqueID = UniqueIDTextField.getText();
      
        
        person.setName(name);
        person.setDate(date);
        person.setFaxNo(faxNo);
        person.setGeographicalData(geographicalData);
        person.setTelPhn1(telPhn1);
        person.setTelPhn2(telPhn2);
        person.setSsnNo(ssnNo);
        person.setEmail1(email1);
        person.setEmail2(email2);
        person.setMedNo(medNo);
        person.setHpbNo(hpbNo);
        person.setBankacc1(bankacc1);
        person.setBankacc2(bankacc2);
        person.setLinkedin(linkedin);
        person.setLicense(license);
        person.setIpAdd(ipAdd);
        person.setVehicleID(vehicleID1);
        person.setLicensePlateNo(licensePlateNo);
        person.setDeviceID(deviceID);
        person.setBioID(bioID);
        person.setSerialNo(serialNo);
        person.setUniqueID(uniqueID);
        person.setPhoto1(pic1Lbl.getIcon());
        person.setPhoto2(pic2Lbl.getIcon());
        if (pic1Lbl.getIcon()==null)
            
            JOptionPane.showConfirmDialog(null, "Please upload photo");
             
        else {
            JOptionPane.showMessageDialog(null, "Person Profile has been saved successfully");
         }
  
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void TelPh2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelPh2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelPh2TextFieldActionPerformed

    private void GeographicDataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeographicDataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeographicDataTextFieldActionPerformed

    private void HealthPlanNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthPlanNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HealthPlanNoTextFieldActionPerformed

    private void BankAccNo1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankAccNo1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankAccNo1TextFieldActionPerformed

    private void Email1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email1TextFieldActionPerformed

    private void BankAccNo2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankAccNo2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankAccNo2TextFieldActionPerformed

    private void TelPh1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelPh1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelPh1TextFieldActionPerformed

    private void DateofBirthTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateofBirthTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateofBirthTextField1ActionPerformed

    private void LicenseNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseNoTextFieldActionPerformed

    private void LinkedInTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkedInTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LinkedInTextFieldActionPerformed

    private void Email2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email2TextFieldActionPerformed

    private void VehicleID1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleID1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleID1TextFieldActionPerformed

    private void VehicleID2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleID2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleID2TextFieldActionPerformed

    private void IPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTextFieldActionPerformed

    private void BiometricTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiometricTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiometricTextFieldActionPerformed

    private void SSNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNTextFieldActionPerformed

    private void FaxNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaxNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaxNoTextFieldActionPerformed

    private void UniqueIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniqueIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniqueIDTextFieldActionPerformed

    private void MedicalNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalNoTextFieldActionPerformed

    private void DeviceID1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceID1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeviceID1TextFieldActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void DeviceID2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceID2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeviceID2TextFieldActionPerformed
  
    private void BroswePic1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroswePic1BtnActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser1 = new JFileChooser();
        chooser1.showOpenDialog(null);
        File file = chooser1.getSelectedFile();
        String path1 = file.getAbsolutePath();
        //Insering image into the JLabel
        Image im1 = Toolkit.getDefaultToolkit().createImage(path1);
        im1 = im1.getScaledInstance(pic1Lbl.getWidth(), pic1Lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i1 = new ImageIcon(im1);
        pic1Lbl.setIcon(i1);
        
    }//GEN-LAST:event_BroswePic1BtnActionPerformed

    private void BroswePic2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroswePic2BtnActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser2 = new JFileChooser();
        chooser2.showOpenDialog(null);
        File file = chooser2.getSelectedFile();
        String path2 = file.getAbsolutePath();
        //Insering image into the JLabel
        Image im2 = Toolkit.getDefaultToolkit().createImage(path2);
        im2 = im2.getScaledInstance(pic2Lbl.getWidth(), pic2Lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(im2);
        pic2Lbl.setIcon(i2);
      
    }//GEN-LAST:event_BroswePic2BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BankAccNo1TextField;
    private javax.swing.JTextField BankAccNo2TextField;
    private javax.swing.JLabel BankAccNoLbl;
    private javax.swing.JLabel BiometricLbl;
    private javax.swing.JTextField BiometricTextField;
    private javax.swing.JButton BroswePic1Btn;
    private javax.swing.JButton BroswePic2Btn;
    private javax.swing.JLabel CreatLbl;
    private javax.swing.JLabel DateofBirthLbl;
    private javax.swing.JTextField DateofBirthTextField1;
    private javax.swing.JTextField DeviceID1TextField;
    private javax.swing.JTextField DeviceID2TextField;
    private javax.swing.JLabel DeviceIDLbl;
    private javax.swing.JTextField Email1TextField;
    private javax.swing.JTextField Email2TextField;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel FaxNoLbl;
    private javax.swing.JTextField FaxNoTextField;
    private javax.swing.JLabel GeographicDataLbl;
    private javax.swing.JTextField GeographicDataTextField;
    private javax.swing.JLabel HealthPlanNoLbl;
    private javax.swing.JTextField HealthPlanNoTextField;
    private javax.swing.JLabel IPLbl;
    private javax.swing.JTextField IPTextField;
    private javax.swing.JLabel LicenseNoLbl;
    private javax.swing.JTextField LicenseNoTextField;
    private javax.swing.JLabel LinkedInLbl;
    private javax.swing.JTextField LinkedInTextField;
    private javax.swing.JLabel MedicalNoLbl;
    private javax.swing.JTextField MedicalNoTextField;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PhotoLbl;
    private javax.swing.JLabel SSNLbl;
    private javax.swing.JTextField SSNTextField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField TelPh1TextField;
    private javax.swing.JTextField TelPh2TextField;
    private javax.swing.JLabel TelPhnLbl;
    private javax.swing.JLabel UniqueIDLbl;
    private javax.swing.JTextField UniqueIDTextField;
    private javax.swing.JTextField VehicleID1TextField;
    private javax.swing.JTextField VehicleID2TextField;
    private javax.swing.JLabel VehicleIdentifierLbl;
    private javax.swing.JLabel pic1Lbl;
    private javax.swing.JLabel pic2Lbl;
    // End of variables declaration//GEN-END:variables

    
    
}
