/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignsHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;

/**
 *
 * @author Seemin
 */
public class CreateVitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalsJPanel
     */
   
    //local variable
    @SuppressWarnings("FieldMayBeFinal")
        
      private VitalSignsHistory vsh;
    
     //parameterized constructor of Vitalsignshistory class
     public CreateVitalsJPanel(VitalSignsHistory vsh) {
         initComponents();
         //assigning global variable to local variable as we used same name 
         this.vsh = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateLbl = new javax.swing.JLabel();
        TemperatureLbl = new javax.swing.JLabel();
        PulseLbl = new javax.swing.JLabel();
        DateLbl = new javax.swing.JLabel();
        BloodPressureLbl = new javax.swing.JLabel();
        BtnSave = new javax.swing.JButton();
        TemperatureTextField = new javax.swing.JTextField();
        BloodPressureTextField = new javax.swing.JTextField();
        PulseTextField = new javax.swing.JTextField();
        DateTextField = new javax.swing.JTextField();

        CreateLbl.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        CreateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateLbl.setText("CREATE VITAL SIGNS");

        TemperatureLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        TemperatureLbl.setText("Temperature :");

        PulseLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PulseLbl.setText("Pulse :");

        DateLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        DateLbl.setText("Date :");

        BloodPressureLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        BloodPressureLbl.setText("Blood Pressure");

        BtnSave.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        TemperatureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureTextFieldActionPerformed(evt);
            }
        });

        PulseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulseTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BloodPressureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PulseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TemperatureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnSave)
                            .addComponent(TemperatureTextField)
                            .addComponent(BloodPressureTextField)
                            .addComponent(PulseTextField)
                            .addComponent(DateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(CreateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(CreateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemperatureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TemperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodPressureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PulseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(BtnSave)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        
        double temperature = Double.parseDouble(TemperatureTextField.getText());
        double bloodPressure = Double.parseDouble(BloodPressureTextField.getText());
        int pulse = Integer.parseInt(PulseTextField.getText());
        String date = DateTextField.getText();
       
       //local object of VitalSigns returning vsh method
        VitalSigns v = vsh.addVital();
        
       //set values that are being input by user as local variables of VitalSIgns Class
       v.setBloodPressure(bloodPressure);
       v.setTemperature(temperature);
       v.setPulse(pulse);
       v.setDate(date);
       //JOptionPane.showMessageDialog(DateTextField, BtnSave);
       JOptionPane.showMessageDialog(null, "Vital Added Successfully");
        
        
        //clear text field
        TemperatureTextField.setText("");
        BloodPressureTextField.setText("");
        PulseTextField.setText("");
        DateTextField.setText("");
        
        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void TemperatureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemperatureTextFieldActionPerformed

    private void PulseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PulseTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloodPressureLbl;
    private javax.swing.JTextField BloodPressureTextField;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel CreateLbl;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JLabel PulseLbl;
    private javax.swing.JTextField PulseTextField;
    private javax.swing.JLabel TemperatureLbl;
    private javax.swing.JTextField TemperatureTextField;
    // End of variables declaration//GEN-END:variables

   
    }
