/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleetCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Seemin
 */
public class CarMngWorkArea extends javax.swing.JPanel {
    private CarFleetCatalog carList;
    private JPanel userProcessContainer;
    /**
     * Creates new form CarMngWorkArea
     */
    CarMngWorkArea(JPanel userProcessContainer, CarFleetCatalog carList) {
        initComponents();
        this.carList = carList ;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageCarBtn = new javax.swing.JButton();
        CreateCarBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        ManageCarBtn.setBackground(new java.awt.Color(255, 255, 255));
        ManageCarBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ManageCarBtn.setText("Manage Cars");
        ManageCarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManageCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCarBtnActionPerformed(evt);
            }
        });

        CreateCarBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateCarBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        CreateCarBtn.setText("Create Car");
        CreateCarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(ManageCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(CreateCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(650, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ManageCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(CreateCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(495, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCarBtnActionPerformed
       CreateCarJPanel panel = new CreateCarJPanel(userProcessContainer,carList);
        userProcessContainer.add("CreateCarJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CreateCarBtnActionPerformed

    private void ManageCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCarBtnActionPerformed
        ManageCarJPanel panel = new ManageCarJPanel(userProcessContainer,carList);
        userProcessContainer.add("ManageCarJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageCarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCarBtn;
    private javax.swing.JButton ManageCarBtn;
    // End of variables declaration//GEN-END:variables
}
