/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarFleetCatalog;
import Business.Car;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Seemin
 */
public class ViewCarJPanel extends javax.swing.JPanel {
    private Car car;
    private JPanel userProcessContainer;
    private CarFleetCatalog carList;
    /**
     * Creates new form ViewCarJPanel
     */
    ViewCarJPanel(JPanel userProcessContainer, Car car) {
        initComponents();
        this.car = car ;
        this.userProcessContainer = userProcessContainer;
        populateCarDetails();
        SaveBtn.setEnabled(false);
        UpdateBtn.setEnabled(true);
    }
    public void populateCarDetails(){
        
        
        txtManufactorerName.setText(car.getManufacturerName());
        txtDateofManufactoring.setText(Integer.toString(car.getDateofManufacturing()));
        txtCity.setText(car.getCity());
        txtSerialNumber.setText(car.getSerialNumber());
        txtModelNumber.setText(car.getModelNumber());
        txtmaxSeats.setText(Integer.toString(car.getMaxNumOfSeats()));
        txtMinseats.setText(Integer.toString(car.getMinNumOfSeats()));
        txtCarAvail.setText(Boolean.toString(car.isCheckAvailability()));
        txtMCExpiry.setText(Boolean.toString(car.isMaintenanceCertificateExpirtDate()));
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModelNumberLbl = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        CityLbl = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        SerialNumberLbl = new javax.swing.JLabel();
        ViewCarLbl = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        ManufactorerNameLbl = new javax.swing.JLabel();
        txtManufactorerName = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        MCExpiryLbl = new javax.swing.JLabel();
        DateofManufactoringLbl = new javax.swing.JLabel();
        txtMCExpiry = new javax.swing.JTextField();
        txtDateofManufactoring = new javax.swing.JTextField();
        carAvailabilitylbl = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        UpdateDateLbl = new javax.swing.JLabel();
        txtUpdateDate = new javax.swing.JTextField();
        txtCarAvail = new javax.swing.JTextField();
        NumberofSeatsLbl1 = new javax.swing.JLabel();
        txtMinseats = new javax.swing.JTextField();
        txtmaxSeats = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        ModelNumberLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        ModelNumberLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ModelNumberLbl.setText("Model Number :");

        txtModelNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtModelNumber.setEnabled(false);

        CityLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        CityLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CityLbl.setText("City :");

        txtCity.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtCity.setEnabled(false);

        SerialNumberLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        SerialNumberLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SerialNumberLbl.setText("Serial Number :");

        ViewCarLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ViewCarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewCarLbl.setText("VIEW CAR ENTRY");
        ViewCarLbl.setFocusable(false);
        ViewCarLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtSerialNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtSerialNumber.setEnabled(false);

        ManufactorerNameLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        ManufactorerNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ManufactorerNameLbl.setText("Manufactorer Name :");

        txtManufactorerName.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtManufactorerName.setEnabled(false);

        backBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        MCExpiryLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        MCExpiryLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MCExpiryLbl.setText("Maintenance Certificate Expiry Date :");

        DateofManufactoringLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        DateofManufactoringLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DateofManufactoringLbl.setText("Date of Manufactoring : ");

        txtMCExpiry.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtMCExpiry.setEnabled(false);

        txtDateofManufactoring.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtDateofManufactoring.setEnabled(false);

        carAvailabilitylbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        carAvailabilitylbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        carAvailabilitylbl.setText("Car Availability :");

        UpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        UpdateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        SaveBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SaveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        UpdateDateLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        UpdateDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UpdateDateLbl.setText("Enter Update Date** :");

        txtUpdateDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtUpdateDate.setEnabled(false);

        txtCarAvail.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtCarAvail.setEnabled(false);

        NumberofSeatsLbl1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        NumberofSeatsLbl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NumberofSeatsLbl1.setText("Number of Seats in Car: ");

        txtMinseats.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtMinseats.setText("Min Seats");
        txtMinseats.setEnabled(false);

        txtmaxSeats.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtmaxSeats.setText("Max Seats");
        txtmaxSeats.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SerialNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSerialNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCity))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ModelNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateofManufactoringLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateofManufactoring)
                                    .addComponent(txtModelNumber)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManufactorerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtManufactorerName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(carAvailabilitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MCExpiryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumberofSeatsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtmaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                                    .addComponent(txtMCExpiry)
                                    .addComponent(txtCarAvail)
                                    .addComponent(txtUpdateDate))))))
                .addGap(308, 308, 308))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(ViewCarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ViewCarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufactorerName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufactorerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateofManufactoring, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateofManufactoringLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SerialNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberofSeatsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MCExpiryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMCExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carAvailabilitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCarAvail, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUpdateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
                
        SaveBtn.setEnabled(true);
        UpdateBtn.setEnabled(false);
        //Enable all fields
        txtManufactorerName.setEnabled(true);
        txtDateofManufactoring.setEnabled(true);
        txtCity.setEnabled(true);
        txtSerialNumber.setEnabled(true);
        txtModelNumber.setEnabled(true);
        txtMinseats.setEnabled(true);
        txtmaxSeats.setEnabled(true);
        txtMCExpiry.setEnabled(true);
        txtCarAvail.setEnabled(true);
        txtUpdateDate.setEnabled(true);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        SaveBtn.setEnabled(false);
        UpdateBtn.setEnabled(true);  
        String LastUpdate = txtUpdateDate.getText();
        
        car.setLastUpdated(LastUpdate);
        car.setManufacturerName(txtManufactorerName.getText());
        car.setDateofManufacturing(Integer.parseInt(txtDateofManufactoring.getText()));
        car.setModelNumber(txtModelNumber.getText());
        car.setCity(txtCity.getText());
        car.setSerialNumber(txtSerialNumber.getText());
        car.setCheckAvailability(Boolean.parseBoolean(txtCarAvail.getText()));
        car.setMaxNumOfSeats(Integer.parseInt(txtmaxSeats.getText()));
        car.setMinNumOfSeats(Integer.parseInt(txtMinseats.getText()));
        car.setMaintenanceCertificateExpirtDate(Boolean.parseBoolean(txtMCExpiry.getText()));
       
        JOptionPane.showMessageDialog(null, "Account updated successfully");
        //Disable all fields
        txtManufactorerName.setEnabled(false);
        txtDateofManufactoring.setEnabled(false);
        txtCity.setEnabled(false);
        txtSerialNumber.setEnabled(false);
        txtModelNumber.setEnabled(false);
        txtMinseats.setEnabled(false);
        txtmaxSeats.setEnabled(false);
        txtMCExpiry.setEnabled(false);
        txtCarAvail.setEnabled(false);
        txtUpdateDate.setEnabled(false);
     
     
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityLbl;
    private javax.swing.JLabel DateofManufactoringLbl;
    private javax.swing.JLabel MCExpiryLbl;
    private javax.swing.JLabel ManufactorerNameLbl;
    private javax.swing.JLabel ModelNumberLbl;
    private javax.swing.JLabel NumberofSeatsLbl1;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel SerialNumberLbl;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel UpdateDateLbl;
    private javax.swing.JLabel ViewCarLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel carAvailabilitylbl;
    private javax.swing.JTextField txtCarAvail;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDateofManufactoring;
    private javax.swing.JTextField txtMCExpiry;
    private javax.swing.JTextField txtManufactorerName;
    private javax.swing.JTextField txtMinseats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtUpdateDate;
    private javax.swing.JTextField txtmaxSeats;
    // End of variables declaration//GEN-END:variables
}
